#!/usr/bin/env bash
# Regenerates packages/types/src/database.ts from the local database.
#
# The header is written here rather than added by hand, so the file is entirely
# reproducible: CI regenerates it and fails on any diff, which is what catches a
# migration that landed without the types being updated. A hand-edited banner
# would make that check fail forever and get disabled.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/packages/types/src/database.ts"

{
  echo "// GENERATED by \`pnpm gen:types\`. Do not hand-edit — the generator"
  echo "// rewrites the whole file, and CI fails if this does not match the schema"
  echo "// in supabase/migrations (CLAUDE.md §3)."
  echo
  cd "$ROOT" && pnpm exec supabase gen types typescript --local
} > "$OUT.tmp"

mv "$OUT.tmp" "$OUT"
echo "gen:types: wrote packages/types/src/database.ts"
